### ISSUE TITLE
Not passing should not always exit with code 1

### ISSUE THREAD

**Issue by mattapperson** [eridem/patata#17]
If you write all your tests ahead of time, you might not want to fail your tests when not everything works, this will clog up a build server that simply needs to generate a report and a progress build of the app. We need a progressBuild cli flag to not fail on test failure

**Comment by eridem** [comment]
Not sure if I understand it well. Can you provide an example?

**Comment by eridem** [comment]
Closed due discontinued conversation.

**Comment by mattapperson** [comment]
In other words this should work more like coverage reports with an option to fail on any non-passing test OR generate a report and exit with exit code 0. Otherwise when run on a CI server all tests must always pass
